package com.ampgconsult.ibcn.data.models

import com.google.firebase.Timestamp

data class InvestorProfile(
    val uid: String = "",
    val displayName: String = "",
    val bio: String = "",
    val preferences: List<String> = emptyList(), // e.g., ["Fintech", "AI", "SaaS"]
    val budgetRange: String = "", // e.g., "$10k - $100k"
    val totalInvested: Double = 0.0,
    val verified: Boolean = false,
    val createdAt: Timestamp = Timestamp.now()
)

data class StartupProfile(
    val id: String = "",
    val ownerId: String = "",
    val name: String = "",
    val description: String = "",
    val pitchDeckUrl: String = "",
    val aiScore: Int = 0, // Generated by OpenAI
    val valuation: Double = 0.0,
    val fundingSought: Double = 0.0,
    val equityOffered: Double = 0.0,
    val stage: String = "MVP", // "Idea", "MVP", "Scaling"
    val demoLink: String = "",
    val industry: String = "",
    val createdAt: Timestamp = Timestamp.now()
)

data class InvestmentRound(
    val id: String = "",
    val startupId: String = "",
    val investorId: String = "",
    val amount: Double = 0.0,
    val equity: Double = 0.0,
    val status: String = "negotiation", // "negotiation", "escrow", "completed", "cancelled"
    val escrowId: String? = null,
    val createdAt: Timestamp = Timestamp.now()
)

data class EscrowAccount(
    val id: String = "",
    val investmentId: String = "",
    val totalAmount: Double = 0.0,
    val releasedAmount: Double = 0.0,
    val status: String = "active", // "active", "completed", "disputed"
    val milestones: List<EscrowMilestone> = emptyList(),
    val createdAt: Timestamp = Timestamp.now()
)

data class EscrowMilestone(
    val id: String = "",
    val description: String = "",
    val amount: Double = 0.0,
    val status: String = "pending", // "pending", "submitted", "approved", "released"
    val proofUrl: String? = null,
    val completedAt: Timestamp? = null
)
